# Generated by Django 5.2 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_wallettransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='affects_wallet',
            field=models.BooleanField(
                default=True,
                help_text='When true, principal adjusts the linked wallet balance.',
            ),
        ),
        migrations.AlterField(
            model_name='debt',
            name='wallet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='debts',
                to='expenses.wallet',
            ),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='wallet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='debt_payments',
                to='expenses.wallet',
            ),
        ),
    ]
