# Generated by Django 5.2 on 2026-06-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_debt_counterparties(apps, schema_editor):
    Debt = apps.get_model("expenses", "Debt")
    Counterparty = apps.get_model("expenses", "Counterparty")

    for debt in Debt.objects.all().iterator():
        name = (debt.counterparty_name or "").strip() or "Unknown"
        cp, _ = Counterparty.objects.get_or_create(
            user_id=debt.user_id,
            name=name,
        )
        debt.counterparty_link_id = cp.id
        debt.save(update_fields=["counterparty_link"])


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_debt_affects_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counterparties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "counterparties",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.RenameField(
            model_name="debt",
            old_name="counterparty",
            new_name="counterparty_name",
        ),
        migrations.AddField(
            model_name="debt",
            name="counterparty_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debts",
                to="expenses.counterparty",
            ),
        ),
        migrations.RunPython(migrate_debt_counterparties, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="debt",
            name="counterparty_name",
        ),
        migrations.RenameField(
            model_name="debt",
            old_name="counterparty_link",
            new_name="counterparty",
        ),
        migrations.AlterField(
            model_name="debt",
            name="counterparty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debts",
                to="expenses.counterparty",
            ),
        ),
    ]
